#!/system/bin/sh
#
#
#################################################################
echo "0,1,2,4,6,15" > /sys/module/lowmemorykiller/parameters/adj;
#################################################################
sync;
sysctl -w kernel.sem=500,512000,100,2048;
sysctl -w kernel.shmmax=268435456;
sysctl -w kernel.msgmni=1024;
sysctl -w net.ipv4.icmp_ignore_bogus_error_responses=1;
sysctl -w net.ipv4.tcp_max_syn_backlog=4096;
sysctl -w net.core.netdev_max_backlog=2500;
sysctl -w net.ipv4.ip_dynaddr=0;
sysctl -w net.ipv4.icmp_echo_ignore_all=1;
sysctl -w net.ipv4.icmp_echo_ignore_broadcasts=1;
sysctl -w net.ipv4.tcp_timestamps=0;
sysctl -w net.ipv4.tcp_tw_reuse=1;
sysctl -w net.ipv4.tcp_sack=1;
sysctl -w net.ipv4.tcp_dsack=1;
sysctl -w net.ipv4.tcp_tw_recycle=1;
sysctl -w net.ipv4.tcp_window_scaling=1;
sysctl -w net.ipv4.tcp_keepalive_probes=5;
sysctl -w net.ipv4.tcp_keepalive_intvl=30;
sysctl -w net.ipv4.tcp_fin_timeout=30;
sysctl -w net.ipv4.tcp_moderate_rcvbuf=1;
sysctl -w vm.page-cluster=3;
sysctl -w vm.laptop_mode=0;
sysctl -w vm.dirty_expire_centisecs=3000;
sysctl -w vm.dirty_expire_centisecs=500;
sysctl -w vm.dirty_background_ratio=65;
sysctl -w vm.dirty_ratio=80;
sysctl -w vm.vfs_cache_pressure=1;
sysctl -w vm.overcommit_memory=1;
sysctl -w vm.oom_kill_allocating_task=0;
sysctl -w vm.panic_on_oom=0;
sysctl -w kernel.panic_on_oops=1;
sysctl -w kernel.panic=0;
sysctl -w vm.drop_caches=0;
sysctl -w kernel.sched_min_granularity_ns=200000;
sysctl -w kernel.sched_latency_ns=400000;
sysctl -w kernel.sched_wakeup_granularity_ns=100000;
#################################################################
