#!/system/bin/sh 


if [ -e /dev/block/mmcblk0p2 ]
then
	sdpartx=$(df -k /dev/block/mmcblk0p2 | tail -n1 | tr -s ' ' | cut -d ' ' -f6)
	rm -R $sdpartx/download
	mkdir $sdpartx/download
	chmod 0771 $sdpartx/download
	chown 1000:2001 $sdpartx/download
	mount -o bind $sdpartx/download /cache/download
fi