#!/system/bin/sh
#
# Sets sdcard read cache size and does several other initializations needed by CM
#

if [ -e /system/bin/log ];
then
    LOGI="log -p i -t mountsd --"
    LOGE="log -p e -t mountsd --"
else
    LOGI=echo
    LOGE=echo
fi

DEFAULT_KB="128KB"
DEFAULT=`/system/xbin/echo $DEFAULT_KB | /system/xbin/sed 's/KB//'`
PROP_KB=`getprop persist.sys.sdcardcachereadsize`
PROP=`/system/xbin/echo $PROP_KB | /system/xbin/sed 's/KB//'`

if [ -n "$PROP_KB" ];
then
	$LOGI "defined sdcard cache read size is $PROP_KB"
	if [ -e /sys/devices/virtual/bdi/179:0/read_ahead_kb ]
	then
		/system/xbin/echo $PROP > /sys/devices/virtual/bdi/179\:0/read_ahead_kb
	fi
else
	$LOGI "no sdcard cache read size defined, using default of $DEFAULT_KB"
	setprop persist.sys.sdcardcachereadsize $DEFAULT_KB
	/system/xbin/echo $DEFAULT > /sys/devices/virtual/bdi/179:0/read_ahead_kb
fi

